version: '2'
services:

#  # Storage System for the Logfiles
  elasticsearch-master:
#    image: elasticsearch:latest
    build: build/elasticsearch
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.elasticsearch"
        fluentd-async-connect: "true"
    ports:
      - 9200:9200
    volumes:
      - ../docker-data/docker-elk/elasticsearch-master/data:/usr/share/elasticsearch/data
    command: elasticsearch -D'ES_JAVA_OPTS=-Xms5g -Xmx5g' -DES_HEAP_SIZE=5g --network.host=0.0.0.0 --node.master=true --node.data=false --node.name="Master_Node" --cluster.name="Main_Cluster" --transport.tcp.compress=true --discovery.zen.minimum_master_nodes=1 --discovery.zen.ping.timeout=30s --discovery.zen.ping.unicast.hosts="elasticsearch-master" --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping_timeout=30s
    networks:
      - elasticsearch

  elasticsearch-slave:
    image: elasticsearch:latest
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.elasticsearch-slave-{{.ID}}"
        fluentd-async-connect: "true"
    ports:
      - 9200
    volumes:
      - ../docker-data/docker-elk/elasticsearch-slave/data:/usr/share/elasticsearch/data
    command: elasticsearch -DES_HEAP_SIZE=2g --network.host=0.0.0.0 --cluster.name="Main_Cluster" --node.master=false --node.data=true --transport.tcp.compress=true --discovery.zen.minimum_master_nodes=1 --discovery.zen.ping.timeout=30s --discovery.zen.ping.multicast.enabled=false --discovery.zen.ping.unicast.hosts="elasticsearch-master" --discovery.zen.ping_timeout=30s
    networks:
      - elasticsearch

  # Interface for building Graphs of the Data in Elasticsearch
  kibana:
    image: kibana:latest
    restart: always
    depends_on: 
      - elasticsearch-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.kibana"
        fluentd-async-connect: "true"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      NODE_OPTIONS: "--max-old-space-size=200"
    links:
      - elasticsearch-master:elasticsearch
    networks:
      - main
      - elasticsearch

  # FluentD Receiver
  fluentd-receiver:
    build: ./build/fluentd
    restart: always
    depends_on:
      - elasticsearch-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.fluentd-receiver"
        fluentd-async-connect: "true"
    environment:
      ELASTICSEARCH_SERVER: elasticsearch # Server to connect to and load ES Templates
    ports:
      - 514:514
      - 514:514/udp
      - 5000:5000
      - 5044:5044
      - 24224:24224
    environment:
      FLUENTD_CONF: "fluentd-receiver.conf"
      FLUENTD_OPT: "-vv"
    volumes:
      - ../docker-data/docker-elk/fluentd-receiver/config:/fluentd/etc
      - ../docker-data/docker-elk/fluentd-receiver/data:/data_log
    cap_add:
      - NET_BIND_SERVICE
    links:
      - elasticsearch-master:elasticsearch
    networks:
      - main
      - elasticsearch

  # Elastic Alerting Program for sending out Emails
  elastalert:
    image: ivankrizsan/elastalert
    cap_add:
      - SYS_TIME
      - SYS_NICE
    depends_on: 
      - elasticsearch-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.elastalert"
        fluentd-async-connect: "true"
    restart: always
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      CONTAINER_TIMEZONE: "America/New_York"
    volumes:
      - ../docker-data/docker-elk/elastalert/rules:/opt/rules
    links:
      - elasticsearch-master:elasticsearch_host
      - elasticsearch-master:elasticsearch
    networks:
      - elasticsearch

networks:
  main:
  elasticsearch:

  ########################
  ###### UTILS ###########
  ########################


  # Curator used to auto-trim elasticsearch data
#  elasticsearch-curator:
#    image: visity/elasticsearch-curator
#    depends_on: 
#      - elasticsearch
#    restart: always
#    environment: 
#      INTERVAL_IN_HOURS: 24
#      OLDER_THAN_IN_DAYS: "7"
#    links:
#      - elasticsearch:es1
#    networks:
#      - main
