version: '2'
services:

  # Master ElasticSearch Node
  elasticsearch-master:
    build: build/elasticsearch
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.elasticsearch-master"
        fluentd-async-connect: "true"
    environment:
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    ports:
      - 9200:9200
    #command: elasticsearch -Enetwork.host=0.0.0.0 -Enode.master=true -Enode.data=false -Enode.name="Master_Node" -Ecluster.name="Main_Cluster" -Etransport.tcp.compress=true -Ehttp.max_content_length=500mb -Ediscovery.zen.master_election.ignore_non_master_pings=true -Ediscovery.zen.fd.ping_timeout=30s -Ethread_pool.bulk.queue_size=5000
    command: elasticsearch --network.host=0.0.0.0 --node.master=true --node.data=false --node.name="Master_Node" --cluster.name="Main_Cluster" --http.max_content_length=500mb --discovery.zen.master_election.ignore_non_master_pings=true --discovery.zen.fd.ping_timeout=30s --thread_pool.bulk.queue_size=5000
    networks:
      - elasticsearch

  # Used by Elasticsearch to connect to in order to load balance requests
#  elasticsearch-client:
#    build: build/elasticsearch
#    restart: always
#    depends_on:
#      - elasticsearch-slave
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: "localhost:24224"
#        tag: "docker.elasticsearch-client-{{.ID}}"
#        fluentd-async-connect: "true"
#    environment:
#      ES_JAVA_OPTS: "-Xms5g -Xmx5g"
#    volumes:
#      - ../docker-data/docker-elk/elasticsearch/data:/usr/share/elasticsearch/data
#    command: elasticsearch -Enetwork.host=0.0.0.0 -Enode.master=false -Enode.data=false -Ecluster.name="Main_Cluster" -Etransport.tcp.compress=true -Ehttp.max_content_length=500mb -Ediscovery.zen.minimum_master_nodes=1 -Ediscovery.zen.ping.unicast.hosts=elasticsearch-master -Ediscovery.zen.master_election.ignore_non_master_pings=true -Ediscovery.zen.fd.ping_timeout=30s -Ethread_pool.bulk.queue_size=5000
#    networks:
#      - elasticsearch

  # Used to create ElasticSearch Slave Nodes, docker-compose scale elasticsearch-slave=X
  elasticsearch-slave:
    build: build/elasticsearch
    restart: always
    depends_on:
      - elasticsearch-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.elasticsearch-slave-{{.ID}}"
        fluentd-async-connect: "true"
    environment:
      ES_JAVA_OPTS: "-Xms5g -Xmx5g"
    volumes:
      - ../docker-data/docker-elk/elasticsearch/data:/usr/share/elasticsearch/data
    #command: elasticsearch -Enetwork.host=0.0.0.0 -Enode.master=false -Enode.data=true -Ecluster.name="Main_Cluster" -Etransport.tcp.compress=true -Ehttp.max_content_length=500mb -Ediscovery.zen.minimum_master_nodes=1 -Ediscovery.zen.ping.unicast.hosts=elasticsearch-master -Ediscovery.zen.master_election.ignore_non_master_pings=true -Ediscovery.zen.fd.ping_timeout=30s -Ethread_pool.bulk.queue_size=5000
    command: elasticsearch --network.host=0.0.0.0 --node.master=false --node.data=true --cluster.name="Main_Cluster" --http.max_content_length=500mb --discovery.zen.minimum_master_nodes=1 --discovery.zen.ping.unicast.hosts=elasticsearch-master --discovery.zen.master_election.ignore_non_master_pings=true --discovery.zen.fd.ping_timeout=30s --thread_pool.bulk.queue_size=5000
    networks:
      - elasticsearch

  # Interface for building Graphs of the Data in Elasticsearch
  kibana:
    build: build/kibana
    restart: always
    depends_on: 
      - elasticsearch-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.kibana"
        fluentd-async-connect: "true"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      NODE_OPTIONS: "--max-old-space-size=200"
    links:
      - elasticsearch-master:elasticsearch
    networks:
      - main
      - elasticsearch

  # FluentD Receiver
  fluentd-receiver:
    build: ./build/fluentd
    restart: always
    depends_on:
      - elasticsearch-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.fluentd-receiver"
        fluentd-async-connect: "true"
    ports:
      - 514:514
      - 514:514/udp
      - 5000:5000
      - 5044:5044
      - 24224:24224
    environment:
      FLUENTD_CONF: "fluentd-receiver.conf"
      FLUENTD_OPT: "-vv"
      ES_SERVER: elasticsearch # Server to connect to and load ES Templates
      ES_USER: "elastic" # Username used to connect to ES to load Templates
      ES_PASSWORD: "changeme" # Password used to connect to ES to load Templates
    volumes:
      - ../docker-data/docker-elk/fluentd-receiver/config:/fluentd/etc
      - ../docker-data/docker-elk/fluentd-receiver/data:/data_log
    cap_add:
      - NET_BIND_SERVICE
    links:
      - elasticsearch-master:elasticsearch
    networks:
      - main
      - elasticsearch

  # Elastic Alerting Program for sending out Emails
  elastalert:
    image: rrspyder/elastalert-docker
    cap_add:
      - SYS_TIME
      - SYS_NICE
    depends_on: 
      - elasticsearch-master
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.elastalert"
        fluentd-async-connect: "true"
    restart: always
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      CONTAINER_TIMEZONE: "America/New_York"
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: changeme
    volumes:
      - ../docker-data/docker-elk/elastalert/rules:/opt/rules
    links:
      - elasticsearch-master:elasticsearch_host
      - elasticsearch-master:elasticsearch
    networks:
      - elasticsearch

networks:
  main:
  elasticsearch:

  ########################
  ###### UTILS ###########
  ########################


  # Curator used to auto-trim elasticsearch data
#  elasticsearch-curator:
#    image: visity/elasticsearch-curator
#    depends_on: 
#      - elasticsearch
#    restart: always
#    environment: 
#      INTERVAL_IN_HOURS: 24
#      OLDER_THAN_IN_DAYS: "7"
#    links:
#      - elasticsearch:es1
#    networks:
#      - main
